// <auto-generated />
namespace BookCarProjectMaster.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dboS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dboS));
        
        string IMigrationMetadata.Id
        {
            get { return "202006080646233_dboS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
